import { DashBoardLayout } from '@/components/layout/dashboard'
import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.className} ${GeistMono.className} bg-[#121214]`}
      >
        <DashBoardLayout>{children}</DashBoardLayout>
      </body>
    </html>
  )
}
