import { Poppins } from 'next/font/google'
import localFont from 'next/font/local'
import type { Metadata } from 'next'

import './globals.css'

const circular = localFont({
  src: '../public/fonts/circular-std-medium-500.woff2',
  variable: '--font-circular',
  preload: true,
})

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500'],
  variable: '--font-poppins',
  preload: true,
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${circular.variable}`}>
        {children}
      </body>
    </html>
  )
}
