import '../styles/globals.css'

import { LoginLayoutComponent } from '@/app/(auth)/layout/public'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <LoginLayoutComponent>
        {children}
        <Toaster />
      </LoginLayoutComponent>
    </>
  )
}
