import { DashBoardLayout } from '@/app/(dashboard)/layout/dashboard'
import type { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function HomeLayout({ children }: { children: ReactNode }) {
  return <DashBoardLayout>{children}</DashBoardLayout>
}
