import '../globals.css'

import { LoginLayoutComponent } from '@/components/layout/public'
import { Toaster } from '@/components/ui/toaster'

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <LoginLayoutComponent>
        {children}
        <Toaster />
      </LoginLayoutComponent>
    </html>
  )
}
